/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueIndexRouteImport } from './routes/queue/index'
import { Route as KioskIndexRouteImport } from './routes/kiosk/index'
import { Route as EvaluationIndexRouteImport } from './routes/evaluation/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CheckInIndexRouteImport } from './routes/check-in/index'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as CheckOutSessionIdRouteImport } from './routes/check-out/$sessionId'
import { Route as StaffDashboardIndexRouteImport } from './routes/staff/dashboard/index'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskIndexRoute = KioskIndexRouteImport.update({
  id: '/kiosk/',
  path: '/kiosk/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationIndexRoute = EvaluationIndexRouteImport.update({
  id: '/evaluation/',
  path: '/evaluation/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInIndexRoute = CheckInIndexRouteImport.update({
  id: '/check-in/',
  path: '/check-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckOutSessionIdRoute = CheckOutSessionIdRouteImport.update({
  id: '/check-out/$sessionId',
  path: '/check-out/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardIndexRoute = StaffDashboardIndexRouteImport.update({
  id: '/staff/dashboard/',
  path: '/staff/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/check-out/$sessionId': typeof CheckOutSessionIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/check-in/': typeof CheckInIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/evaluation/': typeof EvaluationIndexRoute
  '/kiosk/': typeof KioskIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/staff/dashboard/': typeof StaffDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/check-out/$sessionId': typeof CheckOutSessionIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/check-in': typeof CheckInIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/evaluation': typeof EvaluationIndexRoute
  '/kiosk': typeof KioskIndexRoute
  '/queue': typeof QueueIndexRoute
  '/staff/dashboard': typeof StaffDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/check-out/$sessionId': typeof CheckOutSessionIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/check-in/': typeof CheckInIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/evaluation/': typeof EvaluationIndexRoute
  '/kiosk/': typeof KioskIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/staff/dashboard/': typeof StaffDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/check-out/$sessionId'
    | '/staff/login'
    | '/check-in/'
    | '/dashboard/'
    | '/evaluation/'
    | '/kiosk/'
    | '/queue/'
    | '/staff/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/check-out/$sessionId'
    | '/staff/login'
    | '/check-in'
    | '/dashboard'
    | '/evaluation'
    | '/kiosk'
    | '/queue'
    | '/staff/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/check-out/$sessionId'
    | '/staff/login'
    | '/check-in/'
    | '/dashboard/'
    | '/evaluation/'
    | '/kiosk/'
    | '/queue/'
    | '/staff/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CheckOutSessionIdRoute: typeof CheckOutSessionIdRoute
  StaffLoginRoute: typeof StaffLoginRoute
  CheckInIndexRoute: typeof CheckInIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EvaluationIndexRoute: typeof EvaluationIndexRoute
  KioskIndexRoute: typeof KioskIndexRoute
  QueueIndexRoute: typeof QueueIndexRoute
  StaffDashboardIndexRoute: typeof StaffDashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/': {
      id: '/kiosk/'
      path: '/kiosk'
      fullPath: '/kiosk/'
      preLoaderRoute: typeof KioskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/': {
      id: '/evaluation/'
      path: '/evaluation'
      fullPath: '/evaluation/'
      preLoaderRoute: typeof EvaluationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in/': {
      id: '/check-in/'
      path: '/check-in'
      fullPath: '/check-in/'
      preLoaderRoute: typeof CheckInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-out/$sessionId': {
      id: '/check-out/$sessionId'
      path: '/check-out/$sessionId'
      fullPath: '/check-out/$sessionId'
      preLoaderRoute: typeof CheckOutSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard/': {
      id: '/staff/dashboard/'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard/'
      preLoaderRoute: typeof StaffDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CheckOutSessionIdRoute: CheckOutSessionIdRoute,
  StaffLoginRoute: StaffLoginRoute,
  CheckInIndexRoute: CheckInIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EvaluationIndexRoute: EvaluationIndexRoute,
  KioskIndexRoute: KioskIndexRoute,
  QueueIndexRoute: QueueIndexRoute,
  StaffDashboardIndexRoute: StaffDashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
