/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QueueIndexRouteImport } from './routes/queue/index'
import { Route as KioskIndexRouteImport } from './routes/kiosk/index'
import { Route as EvaluationIndexRouteImport } from './routes/evaluation/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CheckInIndexRouteImport } from './routes/check-in/index'
import { Route as StaffLoginRouteImport } from './routes/staff/login'
import { Route as StaffDashboardRouteImport } from './routes/staff/dashboard'
import { Route as CheckOutSessionIdRouteImport } from './routes/check-out/$sessionId'
import { Route as StaffDashboardIndexRouteImport } from './routes/staff/dashboard/index'
import { Route as StaffDashboardQueueRouteImport } from './routes/staff/dashboard/queue'
import { Route as StaffDashboardQuestionsRouteImport } from './routes/staff/dashboard/questions'
import { Route as StaffDashboardAnalyticsRouteImport } from './routes/staff/dashboard/analytics'
import { Route as StaffDashboardAdminRouteImport } from './routes/staff/dashboard/admin'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskIndexRoute = KioskIndexRouteImport.update({
  id: '/kiosk/',
  path: '/kiosk/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationIndexRoute = EvaluationIndexRouteImport.update({
  id: '/evaluation/',
  path: '/evaluation/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInIndexRoute = CheckInIndexRouteImport.update({
  id: '/check-in/',
  path: '/check-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardRoute = StaffDashboardRouteImport.update({
  id: '/staff/dashboard',
  path: '/staff/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckOutSessionIdRoute = CheckOutSessionIdRouteImport.update({
  id: '/check-out/$sessionId',
  path: '/check-out/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffDashboardIndexRoute = StaffDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffDashboardRoute,
} as any)
const StaffDashboardQueueRoute = StaffDashboardQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => StaffDashboardRoute,
} as any)
const StaffDashboardQuestionsRoute = StaffDashboardQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => StaffDashboardRoute,
} as any)
const StaffDashboardAnalyticsRoute = StaffDashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StaffDashboardRoute,
} as any)
const StaffDashboardAdminRoute = StaffDashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => StaffDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/scan': typeof ScanRoute
  '/check-out/$sessionId': typeof CheckOutSessionIdRoute
  '/staff/dashboard': typeof StaffDashboardRouteWithChildren
  '/staff/login': typeof StaffLoginRoute
  '/check-in/': typeof CheckInIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/evaluation/': typeof EvaluationIndexRoute
  '/kiosk/': typeof KioskIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/staff/dashboard/admin': typeof StaffDashboardAdminRoute
  '/staff/dashboard/analytics': typeof StaffDashboardAnalyticsRoute
  '/staff/dashboard/questions': typeof StaffDashboardQuestionsRoute
  '/staff/dashboard/queue': typeof StaffDashboardQueueRoute
  '/staff/dashboard/': typeof StaffDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/scan': typeof ScanRoute
  '/check-out/$sessionId': typeof CheckOutSessionIdRoute
  '/staff/login': typeof StaffLoginRoute
  '/check-in': typeof CheckInIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/evaluation': typeof EvaluationIndexRoute
  '/kiosk': typeof KioskIndexRoute
  '/queue': typeof QueueIndexRoute
  '/staff/dashboard/admin': typeof StaffDashboardAdminRoute
  '/staff/dashboard/analytics': typeof StaffDashboardAnalyticsRoute
  '/staff/dashboard/questions': typeof StaffDashboardQuestionsRoute
  '/staff/dashboard/queue': typeof StaffDashboardQueueRoute
  '/staff/dashboard': typeof StaffDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/scan': typeof ScanRoute
  '/check-out/$sessionId': typeof CheckOutSessionIdRoute
  '/staff/dashboard': typeof StaffDashboardRouteWithChildren
  '/staff/login': typeof StaffLoginRoute
  '/check-in/': typeof CheckInIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/evaluation/': typeof EvaluationIndexRoute
  '/kiosk/': typeof KioskIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/staff/dashboard/admin': typeof StaffDashboardAdminRoute
  '/staff/dashboard/analytics': typeof StaffDashboardAnalyticsRoute
  '/staff/dashboard/questions': typeof StaffDashboardQuestionsRoute
  '/staff/dashboard/queue': typeof StaffDashboardQueueRoute
  '/staff/dashboard/': typeof StaffDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/scan'
    | '/check-out/$sessionId'
    | '/staff/dashboard'
    | '/staff/login'
    | '/check-in/'
    | '/dashboard/'
    | '/evaluation/'
    | '/kiosk/'
    | '/queue/'
    | '/staff/dashboard/admin'
    | '/staff/dashboard/analytics'
    | '/staff/dashboard/questions'
    | '/staff/dashboard/queue'
    | '/staff/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/scan'
    | '/check-out/$sessionId'
    | '/staff/login'
    | '/check-in'
    | '/dashboard'
    | '/evaluation'
    | '/kiosk'
    | '/queue'
    | '/staff/dashboard/admin'
    | '/staff/dashboard/analytics'
    | '/staff/dashboard/questions'
    | '/staff/dashboard/queue'
    | '/staff/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/scan'
    | '/check-out/$sessionId'
    | '/staff/dashboard'
    | '/staff/login'
    | '/check-in/'
    | '/dashboard/'
    | '/evaluation/'
    | '/kiosk/'
    | '/queue/'
    | '/staff/dashboard/admin'
    | '/staff/dashboard/analytics'
    | '/staff/dashboard/questions'
    | '/staff/dashboard/queue'
    | '/staff/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ScanRoute: typeof ScanRoute
  CheckOutSessionIdRoute: typeof CheckOutSessionIdRoute
  StaffDashboardRoute: typeof StaffDashboardRouteWithChildren
  StaffLoginRoute: typeof StaffLoginRoute
  CheckInIndexRoute: typeof CheckInIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EvaluationIndexRoute: typeof EvaluationIndexRoute
  KioskIndexRoute: typeof KioskIndexRoute
  QueueIndexRoute: typeof QueueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/': {
      id: '/kiosk/'
      path: '/kiosk'
      fullPath: '/kiosk/'
      preLoaderRoute: typeof KioskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/': {
      id: '/evaluation/'
      path: '/evaluation'
      fullPath: '/evaluation/'
      preLoaderRoute: typeof EvaluationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in/': {
      id: '/check-in/'
      path: '/check-in'
      fullPath: '/check-in/'
      preLoaderRoute: typeof CheckInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard': {
      id: '/staff/dashboard'
      path: '/staff/dashboard'
      fullPath: '/staff/dashboard'
      preLoaderRoute: typeof StaffDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-out/$sessionId': {
      id: '/check-out/$sessionId'
      path: '/check-out/$sessionId'
      fullPath: '/check-out/$sessionId'
      preLoaderRoute: typeof CheckOutSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/dashboard/': {
      id: '/staff/dashboard/'
      path: '/'
      fullPath: '/staff/dashboard/'
      preLoaderRoute: typeof StaffDashboardIndexRouteImport
      parentRoute: typeof StaffDashboardRoute
    }
    '/staff/dashboard/queue': {
      id: '/staff/dashboard/queue'
      path: '/queue'
      fullPath: '/staff/dashboard/queue'
      preLoaderRoute: typeof StaffDashboardQueueRouteImport
      parentRoute: typeof StaffDashboardRoute
    }
    '/staff/dashboard/questions': {
      id: '/staff/dashboard/questions'
      path: '/questions'
      fullPath: '/staff/dashboard/questions'
      preLoaderRoute: typeof StaffDashboardQuestionsRouteImport
      parentRoute: typeof StaffDashboardRoute
    }
    '/staff/dashboard/analytics': {
      id: '/staff/dashboard/analytics'
      path: '/analytics'
      fullPath: '/staff/dashboard/analytics'
      preLoaderRoute: typeof StaffDashboardAnalyticsRouteImport
      parentRoute: typeof StaffDashboardRoute
    }
    '/staff/dashboard/admin': {
      id: '/staff/dashboard/admin'
      path: '/admin'
      fullPath: '/staff/dashboard/admin'
      preLoaderRoute: typeof StaffDashboardAdminRouteImport
      parentRoute: typeof StaffDashboardRoute
    }
  }
}

interface StaffDashboardRouteChildren {
  StaffDashboardAdminRoute: typeof StaffDashboardAdminRoute
  StaffDashboardAnalyticsRoute: typeof StaffDashboardAnalyticsRoute
  StaffDashboardQuestionsRoute: typeof StaffDashboardQuestionsRoute
  StaffDashboardQueueRoute: typeof StaffDashboardQueueRoute
  StaffDashboardIndexRoute: typeof StaffDashboardIndexRoute
}

const StaffDashboardRouteChildren: StaffDashboardRouteChildren = {
  StaffDashboardAdminRoute: StaffDashboardAdminRoute,
  StaffDashboardAnalyticsRoute: StaffDashboardAnalyticsRoute,
  StaffDashboardQuestionsRoute: StaffDashboardQuestionsRoute,
  StaffDashboardQueueRoute: StaffDashboardQueueRoute,
  StaffDashboardIndexRoute: StaffDashboardIndexRoute,
}

const StaffDashboardRouteWithChildren = StaffDashboardRoute._addFileChildren(
  StaffDashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ScanRoute: ScanRoute,
  CheckOutSessionIdRoute: CheckOutSessionIdRoute,
  StaffDashboardRoute: StaffDashboardRouteWithChildren,
  StaffLoginRoute: StaffLoginRoute,
  CheckInIndexRoute: CheckInIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EvaluationIndexRoute: EvaluationIndexRoute,
  KioskIndexRoute: KioskIndexRoute,
  QueueIndexRoute: QueueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
